### ISSUE TITLE
bt_spec fails on pre 1.7.4 versions of Git

### ISSUE THREAD

**Issue by jfraser** [quad/bt#15]
According to Mandrew this is something to do with git's handling of mirrors changing at 1.7.4. I was using 1.7.0.3.313.g87b3c.
# Spec failure snippet:

```
  /Users/james/.rvm/gems/ruby-1.9.2-p180@bt/gems/grit-2.4.1/lib/grit/git.rb:311:in `native': Command exited with 128: /usr/local/bin/git --git-dir=/var/folders/OA/OAXATDj-EjicTj7GK7PmhU+++TI/-Tmp-/bt20110704-33082-1b76ghe.git fetch origin +refs/bt/*:refs/bt/* (Grit::Git::CommandFailed)
    from /Users/james/.rvm/gems/ruby-1.9.2-p180@bt/gems/grit-2.4.1/lib/grit/git.rb:325:in `method_missing'
    from /Users/james/work/bt/lib/bt/git.rb:109:in `update'
    from /Users/james/work/bt/spec/../bin/bt-results:25:in `block in <main>'
    from /Users/james/work/bt/lib/bt/git.rb:66:in `block in initialize'
    from /Users/james/work/bt/lib/bt/git.rb:66:in `chdir'
    from /Users/james/work/bt/lib/bt/git.rb:66:in `initialize'
    from /Users/james/work/bt/lib/bt/git.rb:47:in `new'
    from /Users/james/work/bt/lib/bt/git.rb:47:in `block in mirror'
    from /Users/james/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
    from /Users/james/work/bt/lib/bt/git.rb:45:in `mirror'
    from /Users/james/work/bt/spec/../bin/bt-results:24:in `<main>'
   D, [2011-07-04T14:08:10.897586 #33082] DEBUG -- : 
   D, [2011-07-04T14:08:10.897859 #33082] DEBUG -- : fatal: 'origin' does not appear to be a git repository
   fatal: The remote end hung up unexpectedly
 # ./spec/bt_spec.rb:354:in `results'
 # ./spec/bt_spec.rb:284:in `block (2 levels) in <top (required)>'
 # ./spec/bt_spec.rb:167:in `block (4 levels) in <top (required)>'
```

**Comment by akiellor** [comment]
I was able to verify this in version 1.6.5. Looks like earlier versions of git don't set up an 'origin' remote when doing a 'clone --bare --shared'.

We have two options I see:
- Make bt set up the origin remote if it does not exist
- Mention in the wiki that bt requires late git 1.7.*

**Comment by jfraser** [comment]
I just reverted to 1.6.5, I'll have a shot at getting it working.
